In [3]:
# 1) импорт библиотек
import pandas as pd

In [4]:
# 2) загрузка датасета
df = pd.read_csv("../data/processed/final_dataset.csv")
df.head()

,date,sku_id,time_of_day,product,stock,supply,prev_stock,sales
0,2026-04-01,10000204,evening,"Соус Сацебели Охотничий «Кинто», 300 г",5.0,0.0,NaN,0.0
1,2026-04-02,10000204,evening,"Соус Сацебели Охотничий «Кинто», 300 г",5.0,0.0,5.0,0.0
2,2026-04-03,10000204,evening,"Соус Сацебели Охотничий «Кинто», 300 г",5.0,0.0,5.0,0.0
3,2026-04-04,10000204,evening,"Соус Сацебели Охотничий «Кинто», 300 г",4.0,0.0,5.0,1.0
4,2026-04-05,10000204,evening,"Соус Сацебели Охотничий «Кинто», 300 г",4.0,0.0,4.0,0.0

In [5]:
# 3) размер таблицы
df.shape

(43377, 8)

In [6]:
# 4) названия столбцов
df.columns.tolist()

['date',
 'sku_id',
 'time_of_day',
 'product',
 'stock',
 'supply',
 'prev_stock',
 'sales']

In [7]:
# 5) проверка дат
df["date"] = pd.to_datetime(df["date"])
print("Минимальная дата:", df["date"].min())
print("Максимальная дата:", df["date"].max())
print("Количество уникальных дат:", df["date"].nunique())

Минимальная дата: 2026-04-01 00:00:00
Максимальная дата: 2026-04-10 00:00:00
Количество уникальных дат: 10

In [8]:
# 6) количество товаров
print("Количество уникальных SKU:", df["sku_id"].nunique())
print("Количество уникальных товаров:", df["product"].nunique())

Количество уникальных SKU: 4804
Количество уникальных товаров: 4809

In [9]:
# 7) базовая статистика
df[["stock", "supply", "sales"]].describe()

              stock        supply         sales
count  43377.000000  43377.000000  43377.000000
mean      12.326746      0.290315      0.491672
std       57.696574      2.768973      1.439019
min        0.180000      0.000000      0.000000
25%        3.000000      0.000000      0.000000
50%        7.000000      0.000000      0.000000
75%       13.000000      0.000000      0.000000
max     3000.000000    240.000000     50.000000

In [10]:
# 8) сколько продаж равно нулю
(df["sales"] == 0).sum()

33225

In [11]:
# 9) топ товаров по суммарным продажам
top_sales = (
    df.groupby(["sku_id", "product"], as_index=False)["sales"]
    .sum()
    .sort_values("sales", ascending=False)
)

top_sales.head(20)

        sku_id                                            product  sales
4001  10104558   Вода «Из Лавки» негазированная артезианская, 5 л  150.0
277       3824  ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...  132.0
2570  10043841  ПФ Держатель для 2-х стаканов формованное воло...  128.0
276       3823  ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...  128.0
1989  10025345                               Зелёный банан, 1 шт.  112.0
1990  10025346                                       Банан, 1 шт.  105.0
610       7605  Йогурт греческий Teos «Савушкин» натуральный 2...   97.0
1296     23410  Фруктовый лёд Взрывной ураган «Бон Пари» апель...   70.0
515       6783             Огурцы короткоплодные хрустящие, 300 г   68.0
531       6957  Крем-десерт «Коровка из Кореновки» с варёной с...   61.0
145       1907   Пирожное бисквитное Kinder Молочный ломтик, 28 г   59.0
3442  10081292  ПФ Стакан ThermoCup Лето (1 рукав - 18 стакано...   58.0
2707  10047545  Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г   57.0
190       2377  Молоко 2,5% «Простоквашино» пастеризованное, 9...   52.0
420       5791  Вафли Kinder Bueno White c молочно-ореховой на...   50.0
843      11760              Вода «Шишкин лес» негазированная, 1 л   49.0
116       1640            Энергетический напиток Red Bull, 250 мл   49.0
1708  10018476  Напиток Cola Original «Черноголовка» газирован...   49.0
3441  10081291  ПФ Стакан ThermoCup Лето (1 рукав - 15 стакано...   49.0
2460  10041731  Напиток функциональный Actimuno гранат 1,5%, 95 г   48.0

In [12]:
# 10) товары без продаж
zero_sales = (
    df.groupby(["sku_id", "product"], as_index=False)["sales"]
    .sum()
)

zero_sales = zero_sales[zero_sales["sales"] == 0]
zero_sales.head(20)

     sku_id                                            product  sales
8      1066  Крем-гель для душа «Дав» глубокое питание и ув...    0.0
9      1068  Гель-скраб-маска Garnier 3 в 1 Чистая кожа с г...    0.0
11     1080  Дезодорант мужской Old Spice Wolfthorn стик, 5...    0.0
13     1088  Зефирчики Классические «Шармэль» в шоколаде, 1...    0.0
14     1101                  Зубная паста Lacalut Aktiv, 75 мл    0.0
15     1110  Зубная щётка для детей Доктор заяц Colgate от ...    0.0
17     1120      Йогурт Epica с манго и семенами чиа 5%, 130 г    0.0
21     1164             Тунец рубленый Fortuna с маслом, 185 г    0.0
25     1180                 Крекер Original Tuc с солью, 100 г    0.0
27     1186                         Лавровый лист Kotanyi, 5 г    0.0
47     1294                 Пастила ванильная «Шармэль», 221 г    0.0
48     1295             Паштет с гусиной печенью «Хаме», 105 г    0.0
63     1349      Рис белый ароматный Басмати «Мистраль», 500 г    0.0
67     1388                      Нектар апельсиновый Rich, 1 л    0.0
72     1412                           Сок Яблоко «Добрый», 1 л    0.0
91     1531              Хлопья овсяные Nordic 1 минута, 500 г    0.0
99     1549  Чай чёрный Golden Ceylon Greenfield в пакетика...    0.0
102    1561  Чай чёрный Earl Grey Ahmad Tea с ароматом берг...    0.0
105    1603  Шоколад молочный Ritter Sport Extra Nut с цель...    0.0
134    1857  Чай зелёный Flying Dragon Greenfield в пакетик...    0.0

In [13]:
# 11) продажа и сортировка
# считаем суммарные продажи по каждому товару
product_sales = (
    df.groupby(["sku_id", "product"], as_index=False)["sales"]
    .sum()
)

# сортируем
product_sales = product_sales.sort_values("sales", ascending=False)

product_sales.head(20)

        sku_id                                            product  sales
4001  10104558   Вода «Из Лавки» негазированная артезианская, 5 л  150.0
277       3824  ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...  132.0
2570  10043841  ПФ Держатель для 2-х стаканов формованное воло...  128.0
276       3823  ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...  128.0
1989  10025345                               Зелёный банан, 1 шт.  112.0
1990  10025346                                       Банан, 1 шт.  105.0
610       7605  Йогурт греческий Teos «Савушкин» натуральный 2...   97.0
1296     23410  Фруктовый лёд Взрывной ураган «Бон Пари» апель...   70.0
515       6783             Огурцы короткоплодные хрустящие, 300 г   68.0
531       6957  Крем-десерт «Коровка из Кореновки» с варёной с...   61.0
145       1907   Пирожное бисквитное Kinder Молочный ломтик, 28 г   59.0
3442  10081292  ПФ Стакан ThermoCup Лето (1 рукав - 18 стакано...   58.0
2707  10047545  Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г   57.0
190       2377  Молоко 2,5% «Простоквашино» пастеризованное, 9...   52.0
420       5791  Вафли Kinder Bueno White c молочно-ореховой на...   50.0
843      11760              Вода «Шишкин лес» негазированная, 1 л   49.0
116       1640            Энергетический напиток Red Bull, 250 мл   49.0
1708  10018476  Напиток Cola Original «Черноголовка» газирован...   49.0
3441  10081291  ПФ Стакан ThermoCup Лето (1 рукав - 15 стакано...   49.0
2460  10041731  Напиток функциональный Actimuno гранат 1,5%, 95 г   48.0

In [14]:
# 12) разделяем товары
def categorize_sales(x):
    if x == 0:
        return "no_sales"
    elif x < 5:
        return "slow"
    elif x < 20:
        return "medium"
    else:
        return "fast"

product_sales["category"] = product_sales["sales"].apply(categorize_sales)

product_sales["category"].value_counts()

category
slow        2020
no_sales    1354
medium      1250
fast         185
Name: count, dtype: int64

In [15]:
# 13) ищем опасные товары
# берём последнюю дату
latest_date = df["date"].max()

# остатки на последнюю дату
latest_stock = df[df["date"] == latest_date][["sku_id", "product", "stock"]].copy()

# объединяем с продажами
risk_products = pd.merge(
    latest_stock,
    product_sales[["sku_id", "product", "sales", "category"]],
    on=["sku_id", "product"],
    how="left"
)

# фильтр
risk_products = risk_products[
    (risk_products["category"].isin(["no_sales", "slow"])) &
    (risk_products["stock"] >= 10)
]

# сортировка
risk_products = risk_products.sort_values("stock", ascending=False)

risk_products.head(30)

,sku_id,product,stock,sales,category
2497,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales
809,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales
808,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales
1681,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales
379,10020530,"Пюре «Бабушкино лукошко» груша с 4 месяцев, 100 г",158.0,2.0,slow
764,10034486,Влажный корм для кошек Sheba говядина паштет в...,115.0,1.0,slow
562,10024793,"Батончик шоколадный белый Snickers, 81 г",93.0,4.0,slow
1558,10056129,"Влажный корм для собак Cesar паштет ягнёнок, 80 г",80.0,4.0,slow
1030,10042224,Сок «Бабушкино лукошко» яблоко-виноград с 6 ме...,79.0,1.0,slow
3501,1662,Яйцо шоколадное Kinder Сюрприз с игрушкой внут...,78.0,3.0,slow
1615,10058442,Печенье протеиновое «Из Лавки» с суфле со вкус...,77.0,0.0,no_sales
842,10036821,"Петрушка сушёная «Галерея вкусов», 7 г",73.0,3.0,slow
3599,18740,"Печенье затяжное Мария «Любятово», 156 г",72.0,1.0,slow
1031,10042277,"Презервативы Maxus 003 экстремально тонкие, 15...",69.0,2.0,slow
3324,1297,"Паштет с мясом птицы «Хаме», 105 г",69.0,1.0,slow
226,10014471,Влажный корм для кошек Sheba Ломтики говядина ...,68.0,1.0,slow
1672,10060888,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales
1673,10060889,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales
3673,19912,"Анчоус сушёно-вяленый Beerka​, 25 г",64.0,4.0,slow
4148,6125,Мыло хозяйственное для стирки детское «Ушастый...,63.0,0.0,no_sales
25,10001890,Кофейный напиток растворимый Cappuccino Carte ...,62.0,1.0,slow
1467,10052107,"Лакомство для собак Woofa Лёгкое говяжье, 100 г",62.0,0.0,no_sales
377,10020518,Фрикадельки «Бабушкино лукошко» из индейки в б...,60.0,0.0,no_sales
142,10007134,"Имбирь молотый «Галерея вкусов», 10 г",59.0,2.0,slow
3233,11336,Влажный корм для собак Cesar курица с зелёными...,59.0,1.0,slow
3773,21672,Мороженое щербет «Ягодка спелая краса» клубник...,59.0,4.0,slow
3513,16725,Батарейки мизинчиковые ААА алкалиновые GP Ultr...,59.0,1.0,slow
3556,17615,"Пакеты для мусора Master Fresh Био 60 л, 20 шт.",58.0,3.0,slow
238,10015775,"Стаканы одноразовые Celesta прозрачные 200 мл,...",55.0,4.0,slow
3531,17144,"Дрожжи сухие Haas быстродействующие, 7 г",55.0,4.0,slow

In [16]:
# 14) средние продажи за день
# считаем количество дней в данных
num_days = df["date"].nunique()

# добавляем средние продажи в день
product_sales["sales_per_day"] = product_sales["sales"] / num_days

product_sales.head()

,sku_id,product,sales,category,sales_per_day
4001,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",150.0,fast,15.0
277,3824,ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...,132.0,fast,13.2
2570,10043841,ПФ Держатель для 2-х стаканов формованное воло...,128.0,fast,12.8
276,3823,ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...,128.0,fast,12.8
1989,10025345,"Зелёный банан, 1 шт.",112.0,fast,11.2

In [17]:
# 15) Опасные товары
risk_products = pd.merge(
    risk_products,
    product_sales[["sku_id", "sales_per_day"]],
    on="sku_id",
    how="left"
)

risk_products.head()

,sku_id,product,stock,sales,category,sales_per_day
0,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales,0.0
1,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales,0.0
2,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales,0.0
3,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales,0.0
4,10020530,"Пюре «Бабушкино лукошко» груша с 4 месяцев, 100 г",158.0,2.0,slow,0.2

In [18]:
# 16) дни покрытия
risk_products["days_of_stock"] = risk_products["stock"] / (risk_products["sales_per_day"] + 0.0001)

risk_products.head()

,sku_id,product,stock,sales,category,sales_per_day,days_of_stock
0,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales,0.0,3.000000e+07
1,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales,0.0,1.200000e+07
2,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales,0.0,1.200000e+07
3,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales,0.0,3.490000e+06
4,10020530,"Пюре «Бабушкино лукошко» груша с 4 месяцев, 100 г",158.0,2.0,slow,0.2,7.896052e+02

In [19]:
# 17) сортировка
risk_products = risk_products.sort_values("days_of_stock", ascending=False)

risk_products.head(30)

,sku_id,product,stock,sales,category,sales_per_day,days_of_stock
0,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales,0.0,30000000.0
1,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales,0.0,12000000.0
2,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales,0.0,12000000.0
3,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales,0.0,3490000.0
10,10058442,Печенье протеиновое «Из Лавки» с суфле со вкус...,77.0,0.0,no_sales,0.0,770000.0
16,10060888,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0
17,10060889,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0
19,6125,Мыло хозяйственное для стирки детское «Ушастый...,63.0,0.0,no_sales,0.0,630000.0
21,10052107,"Лакомство для собак Woofa Лёгкое говяжье, 100 г",62.0,0.0,no_sales,0.0,620000.0
22,10020518,Фрикадельки «Бабушкино лукошко» из индейки в б...,60.0,0.0,no_sales,0.0,600000.0
30,10038555,Влажный корм для собак Cesar Natural Goodness ...,55.0,0.0,no_sales,0.0,550000.0
31,10017281,Мармелад жевательный Страйпсы Chupa Chups кисл...,52.0,0.0,no_sales,0.0,520000.0
33,10022678,"Базилик измельчённый Orient, 7 г",51.0,0.0,no_sales,0.0,510000.0
37,10115924,"ПФ Чай жасминовый (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0
36,10115925,"ПФ Чай зелёный (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0
35,10115926,"ПФ Чай чёрный (1 уп. -50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0
34,10023218,"Петрушка нарезанная Orient, 7 г",50.0,0.0,no_sales,0.0,500000.0
40,10092713,"Мороженое пломбир «Морж» брикет в вафлях, 90 г",49.0,0.0,no_sales,0.0,490000.0
45,17612,Мочалки металлические для посуды Master Fresh ...,48.0,0.0,no_sales,0.0,480000.0
43,10105571,Тунец полосатый Fortuna рубленый с добавлением...,48.0,0.0,no_sales,0.0,480000.0
42,10043274,"Батарейки Opticell AAA, 4 шт.",48.0,0.0,no_sales,0.0,480000.0
52,10105158,Батончик глазированный Chikalab малина с фиста...,45.0,0.0,no_sales,0.0,450000.0
54,10032734,Влажный корм для собак всех пород «Мираторг» E...,44.0,0.0,no_sales,0.0,440000.0
59,5484,Мороженое шоколадное «Вологодский пломбир» в в...,42.0,0.0,no_sales,0.0,420000.0
61,10036209,"Перец чёрный горошек «Галерея вкусов», 10 г",41.0,0.0,no_sales,0.0,410000.0
66,10042616,Влажные салфетки для ухода за кожаными изделия...,40.0,0.0,no_sales,0.0,400000.0
70,5817,Готовый завтрак Колечки радужные Unicorn с фру...,37.0,0.0,no_sales,0.0,370000.0
68,10010426,Средство для мытья посуды Fairy Platinum арбуз...,37.0,0.0,no_sales,0.0,370000.0
74,10095844,Напиток Абрау Винонад Пино Нуар сильногазирова...,36.0,0.0,no_sales,0.0,360000.0
81,10088894,"Десерт глазированный Fit Kit Тройной шоколад, ...",35.0,0.0,no_sales,0.0,350000.0

In [20]:
# 18) формирование рекомендаций по закупке
def purchase_decision(days):
    if days > 30:
        return "no_order"
    elif days > 10:
        return "reduce_order"
    elif days > 5:
        return "normal_order"
    else:
        return "increase_order"

risk_products["decision"] = risk_products["days_of_stock"].apply(purchase_decision)

risk_products.head(30)

,sku_id,product,stock,sales,category,sales_per_day,days_of_stock,decision
0,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales,0.0,30000000.0,no_order
1,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales,0.0,12000000.0,no_order
2,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales,0.0,12000000.0,no_order
3,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales,0.0,3490000.0,no_order
10,10058442,Печенье протеиновое «Из Лавки» с суфле со вкус...,77.0,0.0,no_sales,0.0,770000.0,no_order
16,10060888,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0,no_order
17,10060889,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0,no_order
19,6125,Мыло хозяйственное для стирки детское «Ушастый...,63.0,0.0,no_sales,0.0,630000.0,no_order
21,10052107,"Лакомство для собак Woofa Лёгкое говяжье, 100 г",62.0,0.0,no_sales,0.0,620000.0,no_order
22,10020518,Фрикадельки «Бабушкино лукошко» из индейки в б...,60.0,0.0,no_sales,0.0,600000.0,no_order
30,10038555,Влажный корм для собак Cesar Natural Goodness ...,55.0,0.0,no_sales,0.0,550000.0,no_order
31,10017281,Мармелад жевательный Страйпсы Chupa Chups кисл...,52.0,0.0,no_sales,0.0,520000.0,no_order
33,10022678,"Базилик измельчённый Orient, 7 г",51.0,0.0,no_sales,0.0,510000.0,no_order
37,10115924,"ПФ Чай жасминовый (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order
36,10115925,"ПФ Чай зелёный (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order
35,10115926,"ПФ Чай чёрный (1 уп. -50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order
34,10023218,"Петрушка нарезанная Orient, 7 г",50.0,0.0,no_sales,0.0,500000.0,no_order
40,10092713,"Мороженое пломбир «Морж» брикет в вафлях, 90 г",49.0,0.0,no_sales,0.0,490000.0,no_order
45,17612,Мочалки металлические для посуды Master Fresh ...,48.0,0.0,no_sales,0.0,480000.0,no_order
43,10105571,Тунец полосатый Fortuna рубленый с добавлением...,48.0,0.0,no_sales,0.0,480000.0,no_order
42,10043274,"Батарейки Opticell AAA, 4 шт.",48.0,0.0,no_sales,0.0,480000.0,no_order
52,10105158,Батончик глазированный Chikalab малина с фиста...,45.0,0.0,no_sales,0.0,450000.0,no_order
54,10032734,Влажный корм для собак всех пород «Мираторг» E...,44.0,0.0,no_sales,0.0,440000.0,no_order
59,5484,Мороженое шоколадное «Вологодский пломбир» в в...,42.0,0.0,no_sales,0.0,420000.0,no_order
61,10036209,"Перец чёрный горошек «Галерея вкусов», 10 г",41.0,0.0,no_sales,0.0,410000.0,no_order
66,10042616,Влажные салфетки для ухода за кожаными изделия...,40.0,0.0,no_sales,0.0,400000.0,no_order
70,5817,Готовый завтрак Колечки радужные Unicorn с фру...,37.0,0.0,no_sales,0.0,370000.0,no_order
68,10010426,Средство для мытья посуды Fairy Platinum арбуз...,37.0,0.0,no_sales,0.0,370000.0,no_order
74,10095844,Напиток Абрау Винонад Пино Нуар сильногазирова...,36.0,0.0,no_sales,0.0,360000.0,no_order
81,10088894,"Десерт глазированный Fit Kit Тройной шоколад, ...",35.0,0.0,no_sales,0.0,350000.0,no_order

In [21]:
# 19) расчет рекомендуемого количества закупки

# желаемый запас (например 7 дней)
target_days = 7

# расчет
risk_products["recommended_order"] = (
    risk_products["sales_per_day"] * target_days
) - risk_products["stock"]

# если отрицательное → 0
risk_products["recommended_order"] = risk_products["recommended_order"].apply(lambda x: max(0, x))

risk_products.head(30)

,sku_id,product,stock,sales,category,sales_per_day,days_of_stock,decision,recommended_order
0,10106102,"Крафт-пакет 22х12х29, 70 гр/м2, 500 шт/упак, 5...",3000.0,0.0,no_sales,0.0,30000000.0,no_order,0
1,10035752,ПФ Крышка для стакана ВЗЛП с заглушкой (1 кор....,1200.0,0.0,no_sales,0.0,12000000.0,no_order,0
2,10035751,ПФ Стакан Bubble Cup ВЗЛП 500мл (1 кор- 400шт)...,1200.0,0.0,no_sales,0.0,12000000.0,no_order,0
3,10061115,"ПФ Стакан, 350 мл (1 упаковка - 27 стаканов(ру...",349.0,0.0,no_sales,0.0,3490000.0,no_order,0
10,10058442,Печенье протеиновое «Из Лавки» с суфле со вкус...,77.0,0.0,no_sales,0.0,770000.0,no_order,0
16,10060888,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0,no_order,0
17,10060889,Чайный пакетик для ванны «Из Лавки» с морской ...,66.0,0.0,no_sales,0.0,660000.0,no_order,0
19,6125,Мыло хозяйственное для стирки детское «Ушастый...,63.0,0.0,no_sales,0.0,630000.0,no_order,0
21,10052107,"Лакомство для собак Woofa Лёгкое говяжье, 100 г",62.0,0.0,no_sales,0.0,620000.0,no_order,0
22,10020518,Фрикадельки «Бабушкино лукошко» из индейки в б...,60.0,0.0,no_sales,0.0,600000.0,no_order,0
30,10038555,Влажный корм для собак Cesar Natural Goodness ...,55.0,0.0,no_sales,0.0,550000.0,no_order,0
31,10017281,Мармелад жевательный Страйпсы Chupa Chups кисл...,52.0,0.0,no_sales,0.0,520000.0,no_order,0
33,10022678,"Базилик измельчённый Orient, 7 г",51.0,0.0,no_sales,0.0,510000.0,no_order,0
37,10115924,"ПФ Чай жасминовый (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order,0
36,10115925,"ПФ Чай зелёный (1 уп.-50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order,0
35,10115926,"ПФ Чай чёрный (1 уп. -50 шт.), 1 шт.",50.0,0.0,no_sales,0.0,500000.0,no_order,0
34,10023218,"Петрушка нарезанная Orient, 7 г",50.0,0.0,no_sales,0.0,500000.0,no_order,0
40,10092713,"Мороженое пломбир «Морж» брикет в вафлях, 90 г",49.0,0.0,no_sales,0.0,490000.0,no_order,0
45,17612,Мочалки металлические для посуды Master Fresh ...,48.0,0.0,no_sales,0.0,480000.0,no_order,0
43,10105571,Тунец полосатый Fortuna рубленый с добавлением...,48.0,0.0,no_sales,0.0,480000.0,no_order,0
42,10043274,"Батарейки Opticell AAA, 4 шт.",48.0,0.0,no_sales,0.0,480000.0,no_order,0
52,10105158,Батончик глазированный Chikalab малина с фиста...,45.0,0.0,no_sales,0.0,450000.0,no_order,0
54,10032734,Влажный корм для собак всех пород «Мираторг» E...,44.0,0.0,no_sales,0.0,440000.0,no_order,0
59,5484,Мороженое шоколадное «Вологодский пломбир» в в...,42.0,0.0,no_sales,0.0,420000.0,no_order,0
61,10036209,"Перец чёрный горошек «Галерея вкусов», 10 г",41.0,0.0,no_sales,0.0,410000.0,no_order,0
66,10042616,Влажные салфетки для ухода за кожаными изделия...,40.0,0.0,no_sales,0.0,400000.0,no_order,0
70,5817,Готовый завтрак Колечки радужные Unicorn с фру...,37.0,0.0,no_sales,0.0,370000.0,no_order,0
68,10010426,Средство для мытья посуды Fairy Platinum арбуз...,37.0,0.0,no_sales,0.0,370000.0,no_order,0
74,10095844,Напиток Абрау Винонад Пино Нуар сильногазирова...,36.0,0.0,no_sales,0.0,360000.0,no_order,0
81,10088894,"Десерт глазированный Fit Kit Тройной шоколад, ...",35.0,0.0,no_sales,0.0,350000.0,no_order,0

In [22]:
# 20) рекомендации для всех товаров

# берём последние остатки
latest_date = df["date"].max()

all_products = df[df["date"] == latest_date][["sku_id", "product", "stock"]].copy()

# добавляем продажи
all_products = pd.merge(
    all_products,
    product_sales[["sku_id", "sales", "sales_per_day"]],
    on="sku_id",
    how="left"
)

# считаем дни покрытия
all_products["days_of_stock"] = all_products["stock"] / (all_products["sales_per_day"] + 0.0001)

# применяем решения
all_products["decision"] = all_products["days_of_stock"].apply(purchase_decision)

# считаем рекомендованную закупку
target_days = 7

all_products["recommended_order"] = (
    all_products["sales_per_day"] * target_days
) - all_products["stock"]

all_products["recommended_order"] = all_products["recommended_order"].apply(lambda x: max(0, x))

# сортируем по спросу
all_products = all_products.sort_values("sales_per_day", ascending=False)

all_products.head(30)

,sku_id,product,stock,sales,sales_per_day,days_of_stock,decision,recommended_order
2434,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",9.0,150.0,15.0,0.599996,increase_order,96.0
3986,3824,ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...,635.0,132.0,13.2,48.105696,no_order,0.0
1115,10043841,ПФ Держатель для 2-х стаканов формованное воло...,207.0,128.0,12.8,16.171749,reduce_order,0.0
3985,3823,ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...,1038.0,128.0,12.8,81.093116,no_order,0.0
585,10025345,"Зелёный банан, 1 шт.",26.0,112.0,11.2,2.321408,increase_order,52.4
4301,7605,Йогурт греческий Teos «Савушкин» натуральный 2...,59.0,97.0,9.7,6.082412,normal_order,8.9
3836,23410,Фруктовый лёд Взрывной ураган «Бон Пари» апель...,18.0,70.0,7.0,2.571392,increase_order,31.0
4209,6783,"Огурцы короткоплодные хрустящие, 300 г",2.0,68.0,6.8,0.294113,increase_order,45.6
4224,6957,Крем-десерт «Коровка из Кореновки» с варёной с...,8.0,61.0,6.1,1.311454,increase_order,34.7
3623,1907,"Пирожное бисквитное Kinder Молочный ломтик, 28 г",39.0,59.0,5.9,6.610057,normal_order,2.3
1917,10081292,ПФ Стакан ThermoCup Лето (1 рукав - 18 стакано...,184.0,58.0,5.8,31.723591,no_order,0.0
1243,10047545,"Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г",10.0,57.0,5.7,1.754355,increase_order,29.9
3840,2377,"Молоко 2,5% «Простоквашино» пастеризованное, 9...",27.0,52.0,5.2,5.192208,normal_order,9.4
4122,5791,Вафли Kinder Bueno White c молочно-ореховой на...,32.0,50.0,5.0,6.399872,normal_order,3.0
3257,11760,"Вода «Шишкин лес» негазированная, 1 л",17.0,49.0,4.9,3.469317,increase_order,17.3
1916,10081291,ПФ Стакан ThermoCup Лето (1 рукав - 15 стакано...,27.0,49.0,4.9,5.510092,normal_order,7.3
3499,1640,"Энергетический напиток Red Bull, 250 мл",88.0,49.0,4.9,17.958817,reduce_order,0.0
311,10018476,Напиток Cola Original «Черноголовка» газирован...,47.0,49.0,4.9,9.591641,normal_order,0.0
1015,10041731,"Напиток функциональный Actimuno гранат 1,5%, 95 г",20.0,48.0,4.8,4.166580,increase_order,13.6
3637,1932,Шоколад молочный Kinder Chocolate Country со з...,69.0,48.0,4.8,14.374701,reduce_order,0.0
3498,1632,"Энергетический напиток Adrenaline Rush, 449 мл",15.0,44.0,4.4,3.409013,increase_order,15.8
3806,22343,Батончик злаковый Cornline с клюквой и воздушн...,3.0,44.0,4.4,0.681803,increase_order,27.8
3256,11759,"Вода «Шишкин лес» негазированная, 1.75 л",2.0,43.0,4.3,0.465105,increase_order,28.1
1996,10083748,"Яйцо куриное СО «Лабинское», 10 шт.",22.0,43.0,4.3,5.116160,normal_order,8.1
1136,10044114,"Желе «Из Лавки» со вкусом вишни без сахара, 125 г",34.0,43.0,4.3,7.906793,normal_order,0.0
3882,24416,Кофейный напиток 3в1 «Нескафе» Mild порционный...,206.0,42.0,4.2,49.046451,no_order,0.0
2920,10119611,"Яйца куриные С1 «Стандарт», 10 шт.",58.0,41.0,4.1,14.145996,reduce_order,0.0
2919,10119610,"Яйца куриные СО «Стандарт», 10 шт.",27.0,41.0,4.1,6.585205,normal_order,1.7
3181,1042,"Вода «Святой источник» газированная, 1.5 л",12.0,41.0,4.1,2.926758,increase_order,16.7
840,10036631,"Сырок глазированный «Творобушки» клубника 20%,...",16.0,41.0,4.1,3.902344,increase_order,12.7

In [23]:
# 21) распределение решений по закупке
all_products["decision"].value_counts()

decision
no_order          2355
reduce_order       909
increase_order     621
normal_order       556
Name: count, dtype: int64

In [24]:
# 22) средняя рекомендуемая закупка по типу решения
all_products.groupby("decision")["recommended_order"].describe()

                 count      mean       std  min  25%  50%  75%   max
decision
increase_order   621.0  5.141424  6.794769  0.1  1.5  3.2  6.4  96.0
no_order        2355.0  0.000000  0.000000  0.0  0.0  0.0  0.0   0.0
normal_order     556.0  0.370863  1.050927  0.0  0.0  0.0  0.1   9.4
reduce_order     909.0  0.000000  0.000000  0.0  0.0  0.0  0.0   0.0

In [25]:
# 23) подготовка данных для ML

ml_df = df.copy()

# сортируем по товару и дате
ml_df = ml_df.sort_values(["sku_id", "date"])

# добавляем прошлые продажи (lag)
ml_df["lag_1"] = ml_df.groupby("sku_id")["sales"].shift(1)
ml_df["lag_2"] = ml_df.groupby("sku_id")["sales"].shift(2)

# удаляем пустые строки
ml_df = ml_df.dropna()

ml_df.head()

,date,sku_id,time_of_day,product,stock,supply,prev_stock,sales,lag_1,lag_2
30935,2026-04-03,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,4.0,1.0,2.0,0.0
30936,2026-04-04,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,3.0,0.0,1.0,2.0
30937,2026-04-05,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,3.0,0.0,0.0,1.0
30938,2026-04-06,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,5.0,4.0,3.0,2.0,0.0,0.0
30939,2026-04-07,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,5.0,0.0,5.0,0.0,2.0,0.0

In [28]:
# 24) обучение ML модели

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# признаки (вход)
X = ml_df[["lag_1", "lag_2"]]

# целевая переменная (что предсказываем)
y = ml_df["sales"]

# делим на обучение и тест
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# создаём модель
model = RandomForestRegressor(n_estimators=50, random_state=42)

# обучаем
model.fit(X_train, y_train)

print("Модель обучена")

Модель обучена

In [29]:
# 25) проверка модели

from sklearn.metrics import mean_absolute_error

# прогноз
y_pred = model.predict(X_test)

# ошибка
mae = mean_absolute_error(y_test, y_pred)

print("Средняя ошибка (MAE):", mae)

Средняя ошибка (MAE): 0.6544055250956212

In [30]:
# 26) прогноз продаж с помощью ML

ml_df["predicted_sales"] = model.predict(X)

ml_df.head()

,date,sku_id,time_of_day,product,stock,supply,prev_stock,sales,lag_1,lag_2,predicted_sales
30935,2026-04-03,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,4.0,1.0,2.0,0.0,0.870204
30936,2026-04-04,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,3.0,0.0,1.0,2.0,0.937570
30937,2026-04-05,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,3.0,0.0,3.0,0.0,0.0,1.0,0.553840
30938,2026-04-06,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,5.0,4.0,3.0,2.0,0.0,0.0,0.325079
30939,2026-04-07,1022,evening,Блинчики с творогом «С пылу с жару» замороженн...,5.0,0.0,5.0,0.0,2.0,0.0,0.870204

In [31]:
# 27) средний прогноз продаж по товару

predicted_sales = (
    ml_df.groupby("sku_id", as_index=False)["predicted_sales"]
    .mean()
)

predicted_sales.head()

   sku_id  predicted_sales
0    1022         0.627825
1    1023         0.430913
2    1038         1.115517
3    1041         0.686625
4    1042         3.323805

In [32]:
# 28) добавляем прогноз в all_products

all_products = pd.merge(
    all_products,
    predicted_sales,
    on="sku_id",
    how="left"
)

all_products.head()

,sku_id,product,stock,sales,sales_per_day,days_of_stock,decision,recommended_order,predicted_sales
0,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",9.0,150.0,15.0,0.599996,increase_order,96.0,6.517882
1,3824,ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...,635.0,132.0,13.2,48.105696,no_order,0.0,13.567024
2,10043841,ПФ Держатель для 2-х стаканов формованное воло...,207.0,128.0,12.8,16.171749,reduce_order,0.0,12.989186
3,3823,ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...,1038.0,128.0,12.8,81.093116,no_order,0.0,12.989186
4,10025345,"Зелёный банан, 1 шт.",26.0,112.0,11.2,2.321408,increase_order,52.4,8.017103

In [33]:
# 29) пересчёт закупки через ML

target_days = 7

all_products["ml_recommended_order"] = (
    all_products["predicted_sales"] * target_days
) - all_products["stock"]

all_products["ml_recommended_order"] = all_products["ml_recommended_order"].apply(lambda x: max(0, x))

all_products.head(30)

,sku_id,product,stock,sales,sales_per_day,days_of_stock,decision,recommended_order,predicted_sales,ml_recommended_order
0,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",9.0,150.0,15.0,0.599996,increase_order,96.0,6.517882,36.625175
1,3824,ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...,635.0,132.0,13.2,48.105696,no_order,0.0,13.567024,0.000000
2,10043841,ПФ Держатель для 2-х стаканов формованное воло...,207.0,128.0,12.8,16.171749,reduce_order,0.0,12.989186,0.000000
3,3823,ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...,1038.0,128.0,12.8,81.093116,no_order,0.0,12.989186,0.000000
4,10025345,"Зелёный банан, 1 шт.",26.0,112.0,11.2,2.321408,increase_order,52.4,8.017103,30.119722
5,7605,Йогурт греческий Teos «Савушкин» натуральный 2...,59.0,97.0,9.7,6.082412,normal_order,8.9,8.206979,0.000000
6,23410,Фруктовый лёд Взрывной ураган «Бон Пари» апель...,18.0,70.0,7.0,2.571392,increase_order,31.0,5.769566,22.386960
7,6783,"Огурцы короткоплодные хрустящие, 300 г",2.0,68.0,6.8,0.294113,increase_order,45.6,4.457581,29.203067
8,6957,Крем-десерт «Коровка из Кореновки» с варёной с...,8.0,61.0,6.1,1.311454,increase_order,34.7,3.441831,16.092815
9,1907,"Пирожное бисквитное Kinder Молочный ломтик, 28 г",39.0,59.0,5.9,6.610057,normal_order,2.3,3.284263,0.000000
10,10081292,ПФ Стакан ThermoCup Лето (1 рукав - 18 стакано...,184.0,58.0,5.8,31.723591,no_order,0.0,3.547732,0.000000
11,10047545,"Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г",10.0,57.0,5.7,1.754355,increase_order,29.9,3.945358,17.617507
12,2377,"Молоко 2,5% «Простоквашино» пастеризованное, 9...",27.0,52.0,5.2,5.192208,normal_order,9.4,4.265456,2.858192
13,5791,Вафли Kinder Bueno White c молочно-ореховой на...,32.0,50.0,5.0,6.399872,normal_order,3.0,3.042873,0.000000
14,11760,"Вода «Шишкин лес» негазированная, 1 л",17.0,49.0,4.9,3.469317,increase_order,17.3,3.059389,4.415723
15,10081291,ПФ Стакан ThermoCup Лето (1 рукав - 15 стакано...,27.0,49.0,4.9,5.510092,normal_order,7.3,2.636885,0.000000
16,1640,"Энергетический напиток Red Bull, 250 мл",88.0,49.0,4.9,17.958817,reduce_order,0.0,3.561309,0.000000
17,10018476,Напиток Cola Original «Черноголовка» газирован...,47.0,49.0,4.9,9.591641,normal_order,0.0,2.974695,0.000000
18,10041731,"Напиток функциональный Actimuno гранат 1,5%, 95 г",20.0,48.0,4.8,4.166580,increase_order,13.6,3.988941,7.922587
19,1932,Шоколад молочный Kinder Chocolate Country со з...,69.0,48.0,4.8,14.374701,reduce_order,0.0,2.917597,0.000000
20,1632,"Энергетический напиток Adrenaline Rush, 449 мл",15.0,44.0,4.4,3.409013,increase_order,15.8,2.935904,5.551329
21,22343,Батончик злаковый Cornline с клюквой и воздушн...,3.0,44.0,4.4,0.681803,increase_order,27.8,1.535457,7.748202
22,11759,"Вода «Шишкин лес» негазированная, 1.75 л",2.0,43.0,4.3,0.465105,increase_order,28.1,3.974411,25.820874
23,10083748,"Яйцо куриное СО «Лабинское», 10 шт.",22.0,43.0,4.3,5.116160,normal_order,8.1,3.543946,2.807622
24,10044114,"Желе «Из Лавки» со вкусом вишни без сахара, 125 г",34.0,43.0,4.3,7.906793,normal_order,0.0,4.566577,0.000000
25,24416,Кофейный напиток 3в1 «Нескафе» Mild порционный...,206.0,42.0,4.2,49.046451,no_order,0.0,2.770538,0.000000
26,10119611,"Яйца куриные С1 «Стандарт», 10 шт.",58.0,41.0,4.1,14.145996,reduce_order,0.0,2.992499,0.000000
27,10119610,"Яйца куриные СО «Стандарт», 10 шт.",27.0,41.0,4.1,6.585205,normal_order,1.7,2.602412,0.000000
28,1042,"Вода «Святой источник» газированная, 1.5 л",12.0,41.0,4.1,2.926758,increase_order,16.7,3.323805,11.266632
29,10036631,"Сырок глазированный «Творобушки» клубника 20%,...",16.0,41.0,4.1,3.902344,increase_order,12.7,2.817903,3.725324

In [34]:
# 30) сравнение обычной и ML-рекомендации

comparison = all_products[[
    "sku_id",
    "product",
    "stock",
    "sales_per_day",
    "predicted_sales",
    "recommended_order",
    "ml_recommended_order"
]].copy()

comparison["difference"] = comparison["recommended_order"] - comparison["ml_recommended_order"]

comparison.head(30)

,sku_id,product,stock,sales_per_day,predicted_sales,recommended_order,ml_recommended_order,difference
0,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",9.0,15.0,6.517882,96.0,36.625175,59.374825
1,3824,ПФ крышка пластиковая прозрачная 90 мм (1 уп. ...,635.0,13.2,13.567024,0.0,0.000000,0.000000
2,10043841,ПФ Держатель для 2-х стаканов формованное воло...,207.0,12.8,12.989186,0.0,0.000000,0.000000
3,3823,ПФ крышка белая с носиком 90 мм (1 уп. - 1000 ...,1038.0,12.8,12.989186,0.0,0.000000,0.000000
4,10025345,"Зелёный банан, 1 шт.",26.0,11.2,8.017103,52.4,30.119722,22.280278
5,7605,Йогурт греческий Teos «Савушкин» натуральный 2...,59.0,9.7,8.206979,8.9,0.000000,8.900000
6,23410,Фруктовый лёд Взрывной ураган «Бон Пари» апель...,18.0,7.0,5.769566,31.0,22.386960,8.613040
7,6783,"Огурцы короткоплодные хрустящие, 300 г",2.0,6.8,4.457581,45.6,29.203067,16.396933
8,6957,Крем-десерт «Коровка из Кореновки» с варёной с...,8.0,6.1,3.441831,34.7,16.092815,18.607185
9,1907,"Пирожное бисквитное Kinder Молочный ломтик, 28 г",39.0,5.9,3.284263,2.3,0.000000,2.300000
10,10081292,ПФ Стакан ThermoCup Лето (1 рукав - 18 стакано...,184.0,5.8,3.547732,0.0,0.000000,0.000000
11,10047545,"Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г",10.0,5.7,3.945358,29.9,17.617507,12.282493
12,2377,"Молоко 2,5% «Простоквашино» пастеризованное, 9...",27.0,5.2,4.265456,9.4,2.858192,6.541808
13,5791,Вафли Kinder Bueno White c молочно-ореховой на...,32.0,5.0,3.042873,3.0,0.000000,3.000000
14,11760,"Вода «Шишкин лес» негазированная, 1 л",17.0,4.9,3.059389,17.3,4.415723,12.884277
15,10081291,ПФ Стакан ThermoCup Лето (1 рукав - 15 стакано...,27.0,4.9,2.636885,7.3,0.000000,7.300000
16,1640,"Энергетический напиток Red Bull, 250 мл",88.0,4.9,3.561309,0.0,0.000000,0.000000
17,10018476,Напиток Cola Original «Черноголовка» газирован...,47.0,4.9,2.974695,0.0,0.000000,0.000000
18,10041731,"Напиток функциональный Actimuno гранат 1,5%, 95 г",20.0,4.8,3.988941,13.6,7.922587,5.677413
19,1932,Шоколад молочный Kinder Chocolate Country со з...,69.0,4.8,2.917597,0.0,0.000000,0.000000
20,1632,"Энергетический напиток Adrenaline Rush, 449 мл",15.0,4.4,2.935904,15.8,5.551329,10.248671
21,22343,Батончик злаковый Cornline с клюквой и воздушн...,3.0,4.4,1.535457,27.8,7.748202,20.051798
22,11759,"Вода «Шишкин лес» негазированная, 1.75 л",2.0,4.3,3.974411,28.1,25.820874,2.279126
23,10083748,"Яйцо куриное СО «Лабинское», 10 шт.",22.0,4.3,3.543946,8.1,2.807622,5.292378
24,10044114,"Желе «Из Лавки» со вкусом вишни без сахара, 125 г",34.0,4.3,4.566577,0.0,0.000000,0.000000
25,24416,Кофейный напиток 3в1 «Нескафе» Mild порционный...,206.0,4.2,2.770538,0.0,0.000000,0.000000
26,10119611,"Яйца куриные С1 «Стандарт», 10 шт.",58.0,4.1,2.992499,0.0,0.000000,0.000000
27,10119610,"Яйца куриные СО «Стандарт», 10 шт.",27.0,4.1,2.602412,1.7,0.000000,1.700000
28,1042,"Вода «Святой источник» газированная, 1.5 л",12.0,4.1,3.323805,16.7,11.266632,5.433368
29,10036631,"Сырок глазированный «Творобушки» клубника 20%,...",16.0,4.1,2.817903,12.7,3.725324,8.974676

In [35]:
# 31) товары с наибольшим отличием между подходами

comparison.sort_values("difference", ascending=False).head(20)

,sku_id,product,stock,sales_per_day,predicted_sales,recommended_order,ml_recommended_order,difference
0,10104558,"Вода «Из Лавки» негазированная артезианская, 5 л",9.0,15.0,6.517882,96.0,36.625175,59.374825
4,10025345,"Зелёный банан, 1 шт.",26.0,11.2,8.017103,52.4,30.119722,22.280278
33,24475,Влажный корм для собак Chappi По-домашнему с г...,6.0,4.0,0.325079,22.0,0.000000,22.000000
21,22343,Батончик злаковый Cornline с клюквой и воздушн...,3.0,4.4,1.535457,27.8,7.748202,20.051798
8,6957,Крем-десерт «Коровка из Кореновки» с варёной с...,8.0,6.1,3.441831,34.7,16.092815,18.607185
7,6783,"Огурцы короткоплодные хрустящие, 300 г",2.0,6.8,4.457581,45.6,29.203067,16.396933
86,21440,"Уголь для кальяна Crown кокосовый 25 мм, 18 шт.",4.0,2.8,0.854300,15.6,1.980098,13.619902
35,10047709,Мясные чипсы из куриного филе Сухиничи «Мирато...,7.0,3.9,1.956067,20.3,6.692469,13.607531
58,10022405,"Вода «Горная Вершина» негазированная, 5 л",5.0,3.2,1.356748,17.4,4.497238,12.902762
14,11760,"Вода «Шишкин лес» негазированная, 1 л",17.0,4.9,3.059389,17.3,4.415723,12.884277
138,10005649,Фурацилин для приготовления раствора порошок 2...,2.0,2.2,0.430913,13.4,1.016390,12.383610
47,10049584,"Микс салатов рукола и радиччо, 75 г",8.0,3.4,1.633167,15.8,3.432172,12.367828
11,10047545,"Карпаччо из курицы «Из Лавки» сырокопчёное, 100 г",10.0,5.7,3.945358,29.9,17.617507,12.282493
32,10000627,Влажный корм для кошек с чувствительным пищева...,16.0,4.0,0.516803,12.0,0.000000,12.000000
168,10048352,Мороженое Эйфория «Магнат» маскарпоне и голуби...,3.0,2.0,0.364184,11.0,0.000000,11.000000
30,10083749,"Яйцо куриное С1 «Лабинское», 10 шт.",16.0,4.1,2.564710,12.7,1.952973,10.747027
70,1190,"Лапша быстрого приготовления «Доширак» курица,...",8.0,3.0,1.483981,13.0,2.387867,10.612133
34,10120712,Энергетический напиток Flash Up Zero Mode перс...,7.0,3.9,2.424707,20.3,9.972948,10.327052
45,2017,"Вода «Святой источник» негазированная, 1.5 л",8.0,3.5,2.034327,16.5,6.240290,10.259710
20,1632,"Энергетический напиток Adrenaline Rush, 449 мл",15.0,4.4,2.935904,15.8,5.551329,10.248671

In [37]:
# 32) сохранение финального результата

all_products.to_csv("../outputs/final_recommendations.csv", index=False)